import "./globals.css";
import { Inter } from "@next/font/google";
import { ReactNode } from "react";
const inter = Inter();

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-gray-100">{children}</body>
    </html>
  );
}
